### PR TITLE
Added OmniLRS

### PR DESCRIPTION
**Pull request by AntoineRichard**
This addition to the SpaceROS demos brings photo-real rendering specifically designed for long lunar traverses.
The repository attached builds upon Isaac sim to provide a lunar simulation tailored for testing and validating navigation and localization problems. One of the key feature is for rovers to drive tens of kilometers with a very high terrain resolution of up to 2cm per texel. 

The added submodule tracks the main branch of OmniLRS.

OmniLRS offers the following:
- Using LRO generated DEM to create a base low resolution terrain (usually 5mpp)
- Using seeded procedural generation algorithms to augment that base terrain (2cmpp)
- Using seeded procedural generation to scatter rocks on the terrain (up to 1million rocks can be generate in the robots vicinity)
- Repeatable procedural generation, that is if the robots drives twice at the same place the environment will look exactly the same.
- Home made terrain engine using geometry clip maps allowing the rendering of extremely large environments while offering high local resolution. For instance, rendering an LRO DEM of 200km, while having a local resolution of 2cm.
- Use JPL's ephemerides to accurately position the Sun and Earth given the current lunar coordinates.
- Deformable terrains for small scale environments
- Fully open source code, as well as open data simulation
- Complete API and code documentation
- Textures generated using photogrammetry of regolith simulant.
- Docker containers
- Easy install scripts
- And more!

Here are 3 videos showcasing the simulation:
- Large Scale terrains: https://www.youtube.com/watch?v=3m78fO5uXwA&ab_channel=SnT-SpaceR
- Deformable terrains: https://www.youtube.com/watch?v=TpzD0h-5hv4&ab_channel=SpaceRoboticsLab
- First release: https://www.youtube.com/watch?v=PebUZjm0WuA&ab_channel=SpaceRoboticsLab

Original repository:
https://github.com/AntoineRichard/OmniLRS

### CODE REVIEW

**Comment by martincerven** [comment]
Cool! SpaceROS is under Apache license, what license is  [this](https://github.com/AntoineRichard/OmniLRS?tab=License-1-ov-file)?

 I'm asking because Isaac Sim is [proprietary SW](https://docs.omniverse.nvidia.com/isaacsim/latest/common/NVIDIA_Omniverse_License_Agreement.html), although data/settings generated are probably free.

**Comment by AntoineRichard** [comment]
The simulation itself is using BSD 3-Clause. I'm not super familiar with these things :D

**Comment by gbiggs** [comment]
What is the reason for adding this as a submodule?

Given the independence of the target repository, it would be better to leave it as a separate package and rely on dependency pulling through colcon.

**Comment by AntoineRichard** [comment]
Hi! I made a submodule as I thought it would be the best way to keep track of the main branch of this repository. Though I'm definitely open to other suggestions! Let me know what's the best way to move forward, and I'll make the appropriate changes.

**Comment by gbiggs** [comment]
The ROS world prefers to package things individually and pull them in at build- or install-time as needed rather than create monolithic repositories, which is what git's submodules do. [See here for more info](https://docs.ros.org/en/jazzy/Tutorials/Beginner-Client-Libraries/Colcon-Tutorial.html).

**Comment by AntoineRichard** [comment]
Right, makes sense. Just to confirm I understood properly. I should add a new ROS package inside this repo that will pull the OmniLRS dependency automatically when built/installed.

I would assume the proper way to doing this is to create a script that would be executed before/after the build/install.
And this could be done by adding it inside the setup.cfg of a `ament_python` package?
Would that be acceptable?

**Comment by gbiggs** [comment]
You need to create a new package in your existing repository or a new repository that will provide OmniLRS. Then one or more of the packages in this repository can specify it as a dependency. If nothing in this repository uses OmniLRS, then nothing in this repository needs to be modified.

**Comment by AntoineRichard** [comment]
I see, I'll match a more ROS-style workfllow. Thanks for your time :)

**Comment by gbiggs** [comment]
Happy to help, and thanks for contributing!

**Pull request closed without merging**
